### ISSUE TITLE
[Bug]: Middleware does not run with netlify-cli

### ISSUE THREAD

**Issue by BrandonALittle** [netlify/next-runtime#1824]
### Summary

NextJS version 13

I'm running my site locally with netlify-cli. I have middleware that runs perfectly fine with `next dev`, but does not even seem to exist when running `netlify dev`.

### Steps to reproduce

1. Create a middleware inside a NextJS v13 app
2. Run `netlify dev`
3. Load the app
4. See that the middleware doesn't run

### Next Runtime version

4.29.2

### More information about your build

- [X] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hey. If your middleware is in `src`, could you try moving it into the top level? We haven't added support for middleware in the src directory yet in dev

**Comment by BrandonALittle** [comment]
My middleware was in the `src` folder. I moved it, and it does get run, though the app doesn't load due to a `this._headers.getAll` is not a function error.

**Comment by ascorbic** [comment]
Have you manually installed the runtime? Which version is it showing as using?

**Comment by BrandonALittle** [comment]
One thing to point out is that the middleware runs when deployed via Netlify, even though the middleware on the deployed site is in the `src` folder. It's only locally that it doesn't run.

**Comment by BrandonALittle** [comment]
Everything seems to work fine with NextJS v13.0.0 and `middleware.ts` at the root. It seems to be an issue with NextJS v13.0.3 & the plugin. Netlify deployments don't seem to have any issue with middleware in `src` and v13.0.3, though.
