### ISSUE TITLE
[Bug]: Error: Cannot find module 'follow-redirects'

### ISSUE THREAD

**Issue by elliottsj** [netlify/next-runtime#1834]
### Summary

This error page is rendered upon visiting our app:

![image](https://user-images.githubusercontent.com/2177366/206031303-b8fda13f-71f0-4f07-8269-fa6a2a7b3f07.png)

```
Runtime.ImportModuleError - Error: Cannot find module 'follow-redirects' Require stack: - /var/task/apps/dashboard/.netlify/functions-internal/___netlify-handler/handlerUtils.js - /var/task/apps/dashboard/.netlify/functions-internal/___netlify-handler/___netlify-handler.js - /var/task/___netlify-handler.js - /var/runtime/index.mjs
```

Stack trace:

```
Runtime.ImportModuleError: Error: Cannot find module 'follow-redirects'
Require stack:
- /var/task/apps/dashboard/.netlify/functions-internal/___netlify-handler/handlerUtils.js
- /var/task/apps/dashboard/.netlify/functions-internal/___netlify-handler/___netlify-handler.js
- /var/task/___netlify-handler.js
- /var/runtime/index.mjs
    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)
    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)
    at async start (file:///var/runtime/index.mjs:1200:23)
    at async file:///var/runtime/index.mjs:1206:1
```

Netlify internal ID: `01GKMNY9325XC365GG3KHDAQNX`.

### Steps to reproduce

Use pnpm and deploy a site using the Netlify CLI. The command we are using is:

```
netlify deploy --build --prod --auth $NETLIFY_AUTH_TOKEN --site $DASHBOARD_NETLIFY_SITE_ID
```

Using netlify-cli@12.0.10 and @netlify/plugin-nextjs@4.29.3.

### Next Runtime version

4.29.3

### More information about your build

- [X] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
[build]
  command = "pnpm run build"

[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "16.18.0"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains;"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "object-src 'none'; base-uri 'none';"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
import { getCommonEnvVars } from '@cohere-ai/utils/nextConfig.mjs';
import { PHASE_PRODUCTION_BUILD, PHASE_PRODUCTION_SERVER } from 'next/constants.js';

import nextTranspileModules from 'next-transpile-modules';
const withTM = nextTranspileModules([
  '@cohere-ai/ui',
  '@cohere-ai/blobheart-client',
  '@cohere-ai/finetune-client',
  '@cohere-ai/utils',
  '@cohere-ai/platform-components',
]);

const getNextConfig = (phase) => {
  if (phase === PHASE_PRODUCTION_BUILD || phase === PHASE_PRODUCTION_SERVER) {
    console.info('Next.js environment variables:', getCommonEnvVars(process.env));
  }

  return withTM({
    reactStrictMode: true,
    async redirects() {
      return [
        {
          source: '/confirm-email',
          destination: '/welcome/confirm-email',
          permanent: true,
        },
        {
          source: '/login',
          destination: '/welcome/login',
          permanent: true,
        },
        {
          source: '/register',
          destination: '/welcome/register',
          permanent: true,
        },
        {
          source: '/terms-of-use',
          destination: 'https://cohere.ai/terms-of-use',
          permanent: true,
        },
        {
          source: '/privacy',
          destination: 'https://cohere.ai/privacy',
          permanent: true,
        },
        {
          source: '/finetune/:path*',
          destination: '/models/custom/:path*',
          permanent: true,
        },
      ];
    },
  });
};

export default getNextConfig;
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
Dec 6, 04:58:57 PM: 2022-12-06T21:58:57.636Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'follow-redirects'\nRequire stack:\n- /var/task/apps/dashboard/.netlify/functions-internal/___netlify-handler/handlerUtils.js\n- /var/task/apps/dashboard/.netlify/functions-internal/___netlify-handler/___netlify-handler.js\n- /var/task/___netlify-handler.js\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'follow-redirects'","Require stack:","- /var/task/apps/dashboard/.netlify/functions-internal/___netlify-handler/handlerUtils.js","- /var/task/apps/dashboard/.netlify/functions-internal/___netlify-handler/___netlify-handler.js","- /var/task/___netlify-handler.js","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)","    at async start (file:///var/runtime/index.mjs:1200:23)","    at async file:///var/runtime/index.mjs:1206:1"]}Dec 6, 04:58:57 PM: Unknown application error occurred
Runtime.ImportModuleError
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by elliottsj** [comment]
I believe this is introduced by https://github.com/netlify/next-runtime/pull/1719. Perhaps the `follow-redirects` npm package is not installed as expected when using pnpm.

**Comment by ericapisani** [comment]
Hi @elliottsj ,

Thanks for logging a ticket and the detailed summary. Are you able to provide a minimal repro project that exhibits the issue? I've unfortunately not been able to reproduce this with one of our demo sites and installing the node modules using `pnpm` rather than `npm`

**Comment by ascorbic** [comment]
If using pnpm, have you enabled hoisting? See this: https://github.com/netlify/next-runtime#using-with-pnpm

**Comment by sarahetter** [comment]
As we haven't heard back in 3 weeks, I'm closing this issue. If you're still having problems, please don't hesitate to re-open.

**Comment by nickytonline** [comment]
I'm currently getting this issue testing out a bug in Next 13 with an ISR page in the app dir. I'm using npm, but I also tried pnpm with hoisting as mentioned, but the issue persists. Not sure what the solution is yet, but I'm going to reopen this as it's blocking me test another issue.

**Comment by nickytonline** [comment]
I had forgot to save the `.npmrc` file which is why it wasn't working with pnpm or npm. After that it was all good. So just confirming that enabling hoisting via a `.npmrc` file works

`.nprmc`
```
public-hoist-pattern[]=*

```

**Comment by elliottsj** [comment]
Thanks for looking into this, I can confirm that setting

```
public-hoist-pattern[] = follow-redirects
```

in `.npmrc` works as a workaround.

Although, in my opinion, requiring `public-hoist-pattern` is an anti-practice, because it defeats the benefits of pnpm's strict module layout.

In particular, if my application happens to depend on a different version of the *follow-redirects* package than *@netlify/plugin-nextjs*, let's say a hypothetical v2.0.0, then the Netlify runtime will import that instead of the expected v1.15.2.

To correctly support pnpm, public-hoist-pattern should not be required.
